#!/bin/sh
# Remove everything `sfdk build` / qmake scatters into the source tree.
# Everything deleted here is regenerated by the next build — no source is touched.
# Run from anywhere:  sh clean.sh
cd "$(dirname "$0")" || exit 1

rm -rf .build RPMS .sfdk installroot
rm -f  Makefile Makefile.* .qmake.stash documentation.list
rm -f  *.o moc_*.cpp moc_*.h qrc_*.cpp ui_*.h
rm -f  harbour-fintune          # the compiled binary at the project root

echo "Cleaned build artifacts from $(pwd)"
